import type { INodeProperties } from 'n8n-workflow';

const SERVICE_URL_DESCRIPTION =
	'OData service path (e.g. /sap/opu/odata/sap/API_BUSINESS_PARTNER), absolute URL, or the technical service name (e.g. API_BUSINESS_PARTNER)';

const showOdata = (operations: string[]) => ({
	show: { resource: ['odata'], operation: operations },
});

/** All node parameters — resource → operation → fields, plus per-operation options. */
export const properties: INodeProperties[] = [
	{
		displayName: 'Resource',
		name: 'resource',
		type: 'options',
		noDataExpression: true,
		options: [
			{ name: 'Discovery', value: 'discovery' },
			{ name: 'IDoc', value: 'idoc' },
			{ name: 'OData', value: 'odata' },
			{ name: 'Tool', value: 'tool' },
		],
		default: 'odata',
	},

	// -----------------------------------------------------------------------
	// OData
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['odata'] } },
		options: [
			{
				name: 'Batch',
				value: 'batch',
				description: 'Run several operations in one OData $batch request',
				action: 'Run a batch request',
			},
			{
				name: 'Call Function',
				value: 'function',
				description: 'Call a V2 function import or a V4 action/function',
				action: 'Call a function import or action',
			},
			{
				name: 'Create',
				value: 'create',
				description: 'Create an entity (deep insert supported)',
				action: 'Create an entity',
			},
			{
				name: 'Delete',
				value: 'delete',
				description: 'Delete an entity by key',
				action: 'Delete an entity',
			},
			{
				name: 'Download Media',
				value: 'downloadMedia',
				description: 'Download the raw bytes of a media entity (e.g. an attachment) into a binary field',
				action: 'Download a media entity',
			},
			{
				name: 'Query',
				value: 'query',
				description: 'Query an entity set with $filter, $select, $expand, $orderby, $top, $skip',
				action: 'Query an entity set',
			},
			{
				name: 'Read',
				value: 'read',
				description: 'Read one entity by key',
				action: 'Read an entity',
			},
			{
				name: 'Update',
				value: 'update',
				description: 'Update fields of an entity by key (ETag handled by the server)',
				action: 'Update an entity',
			},
			{
				name: 'Upload Media',
				value: 'uploadMedia',
				description: 'Upload a binary field as raw bytes into a media entity (e.g. an attachment)',
				action: 'Upload to a media entity',
			},
		],
		default: 'query',
	},
	{
		displayName: 'Service URL',
		name: 'serviceUrl',
		type: 'string',
		required: true,
		default: '',
		placeholder: '/sap/opu/odata/sap/API_BUSINESS_PARTNER',
		description: SERVICE_URL_DESCRIPTION,
		displayOptions: {
			show: {
				resource: ['odata', 'discovery'],
				operation: [
					'query',
					'read',
					'create',
					'update',
					'delete',
					'function',
					'batch',
					'uploadMedia',
					'downloadMedia',
					'listServices',
					'getMetadata',
				],
			},
		},
	},
	{
		displayName: 'Entity Set',
		name: 'entitySet',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'A_BusinessPartner',
		description: 'Entity set name inside the service',
		displayOptions: showOdata(['query', 'read', 'create', 'update', 'delete', 'uploadMedia', 'downloadMedia']),
	},
	{
		displayName: 'Key',
		name: 'key',
		type: 'json',
		required: true,
		default: '{\n  "BusinessPartner": "1000001"\n}',
		description: 'Entity key as JSON object — one property per key field',
		displayOptions: showOdata(['read', 'update', 'delete', 'downloadMedia']),
	},
	{
		displayName: 'Data',
		name: 'data',
		type: 'json',
		required: true,
		default: '{\n  "BusinessPartnerCategory": "2",\n  "BusinessPartnerName": "Example GmbH"\n}',
		description:
			'Entity data as JSON object. For a deep insert, nest the child entities under their navigation property (e.g. to_Item: [...]).',
		displayOptions: showOdata(['create']),
	},
	{
		displayName: 'Data',
		name: 'data',
		type: 'json',
		required: true,
		default: '{\n  "BusinessPartnerName": "New Name"\n}',
		description: 'Fields to update as JSON object',
		displayOptions: showOdata(['update']),
	},
	{
		displayName: 'Input Binary Field',
		name: 'binaryPropertyName',
		type: 'string',
		required: true,
		default: 'data',
		placeholder: 'data',
		hint: 'Name of the binary field on the incoming item that carries the file',
		description:
			'Which binary field of the incoming item holds the file. n8n names it "data" unless a previous node set something else.',
		displayOptions: showOdata(['uploadMedia']),
	},
	{
		displayName: 'Object Headers',
		name: 'jsonHeaders',
		type: 'json',
		default:
			'{\n  "BusinessObjectTypeName": "BUS2032",\n  "LinkedSAPObjectKey": "0000012345",\n  "DocumentInfoRecordDocType": "PDF"\n}',
		description:
			'Headers that tell SAP which object the file belongs to. A JSON object, because empty values must be omitted entirely — an empty header makes SAP answer with a message that reads like a missing authorisation and is none. LinkedSAPObjectKey goes out ten digits wide with leading zeros; a sales order is BUS2032.',
		displayOptions: showOdata(['uploadMedia']),
	},
	{
		displayName: 'Output Binary Field',
		name: 'binaryPropertyName',
		type: 'string',
		required: true,
		default: 'data',
		placeholder: 'data',
		description: 'Name of the binary field the downloaded file is written to',
		displayOptions: showOdata(['downloadMedia']),
	},
	{
		displayName: 'Upload Options',
		name: 'uploadOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: showOdata(['uploadMedia']),
		options: [
			{
				displayName: 'Content Type',
				name: 'contentType',
				type: 'string',
				default: '',
				placeholder: 'application/pdf',
				description:
					'Overrides the content type from the binary metadata. Leave empty to use what the incoming item carries.',
			},
			{
				displayName: 'File Name',
				name: 'fileName',
				type: 'string',
				default: '',
				placeholder: 'auftragsbestaetigung.pdf',
				description:
					'Overrides the file name from the binary metadata. Goes out as the Slug header.',
			},
		],
	},
	{
		displayName: 'Download Options',
		name: 'downloadOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: showOdata(['downloadMedia']),
		options: [
			{
				displayName: 'Request Without $Value Path',
				name: 'withoutValuePath',
				type: 'boolean',
				default: false,
				description:
					'Whether to request the entity path without the trailing /$value. Only needed when the service serves the bytes directly under the entity path.',
			},
		],
	},
	{
		displayName: 'Split Results Into Items',
		name: 'splitResults',
		type: 'boolean',
		default: true,
		description:
			'Whether to output one item per result row. When off, one item with results, count and paging info is returned.',
		displayOptions: showOdata(['query']),
	},
	{
		displayName: 'Query Options',
		name: 'queryOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: showOdata(['query']),
		options: [
			{
				displayName: 'Expand',
				name: 'expand',
				type: 'string',
				default: '',
				placeholder: 'to_BusinessPartnerAddress',
				description: 'Navigation properties to expand, comma-separated',
			},
			{
				displayName: 'Filter',
				name: 'filter',
				type: 'string',
				default: '',
				placeholder: "Country eq 'DE' and BusinessPartnerCategory eq '2'",
				description: 'OData $filter expression',
			},
			{
				displayName: 'Max Pages',
				name: 'maxPages',
				type: 'number',
				default: 10,
				description: 'Maximum server-side pagination pages to follow',
			},
			{
				displayName: 'Order By',
				name: 'orderby',
				type: 'string',
				default: '',
				placeholder: 'CreationDate desc',
				description: 'OData $orderby expression',
			},
			{
				displayName: 'Select',
				name: 'select',
				type: 'string',
				default: '',
				placeholder: 'BusinessPartner,BusinessPartnerName',
				description: 'Properties to return, comma-separated',
			},
			{
				displayName: 'Skip',
				name: 'skip',
				type: 'number',
				default: 0,
				description: 'Number of rows to skip (paging)',
			},
			{
				displayName: 'Top',
				name: 'top',
				type: 'number',
				default: 50,
				typeOptions: { minValue: 1, maxValue: 1000 },
				description: 'Maximum number of rows to return (server default 50, hard cap 1000)',
			},
		],
	},
	{
		displayName: 'Read Options',
		name: 'readOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: showOdata(['read']),
		options: [
			{
				displayName: 'Expand',
				name: 'expand',
				type: 'string',
				default: '',
				description: 'Navigation properties to expand, comma-separated',
			},
			{
				displayName: 'Select',
				name: 'select',
				type: 'string',
				default: '',
				description: 'Properties to return, comma-separated',
			},
		],
	},
	{
		displayName: 'Function Name',
		name: 'functionName',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'GetBusinessPartnerCount',
		description:
			'V2 function import name, or V4 action/function name (include the namespace for bound operations)',
		displayOptions: showOdata(['function']),
	},
	{
		displayName: 'Parameters',
		name: 'parameters',
		type: 'json',
		default: '{}',
		description: 'Function/action parameters as JSON object',
		displayOptions: showOdata(['function']),
	},
	{
		displayName: 'Function Options',
		name: 'functionOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: showOdata(['function']),
		options: [
			{
				displayName: 'Entity Set (V4 Bound)',
				name: 'entitySet',
				type: 'string',
				default: '',
				description: 'Entity set for V4 bound actions/functions',
			},
			{
				displayName: 'HTTP Method',
				name: 'httpMethod',
				type: 'options',
				options: [
					{ name: 'GET', value: 'GET' },
					{ name: 'POST', value: 'POST' },
				],
				default: 'POST',
				description: 'Override the HTTP method (V2: from metadata or POST by default)',
			},
			{
				displayName: 'Is V4 Function',
				name: 'isFunction',
				type: 'boolean',
				default: false,
				description: 'Whether this is a V4 Function (GET) instead of an Action (POST). Ignored for V2.',
			},
			{
				displayName: 'Key (V4 Bound)',
				name: 'key',
				type: 'json',
				default: '',
				description: 'Entity key as JSON object for V4 bound actions/functions',
			},
		],
	},
	{
		displayName: 'Operations',
		name: 'operations',
		type: 'json',
		required: true,
		default:
			'[\n  { "method": "GET", "entitySet": "A_BusinessPartner", "key": { "BusinessPartner": "1000001" } }\n]',
		description:
			'Array of batch operations as JSON. See the sap_batch documentation of the server for the operation shape.',
		displayOptions: showOdata(['batch']),
	},

	// -----------------------------------------------------------------------
	// Discovery
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['discovery'] } },
		options: [
			{
				name: 'Discover Services',
				value: 'discoverServices',
				description: 'Search the service catalog by text and business category',
				action: 'Discover services',
			},
			{
				name: 'Get Metadata',
				value: 'getMetadata',
				description: 'Entity types, properties, keys and navigation properties of a service',
				action: 'Get service metadata',
			},
			{
				name: 'List Entity Sets',
				value: 'listServices',
				description: 'Entity sets of one OData service',
				action: 'List entity sets of a service',
			},
			{
				name: 'Test Connection',
				value: 'testConnection',
				description: 'Diagnose DNS, TLS, authentication, client and catalog access stage by stage',
				action: 'Test the SAP connection',
			},
		],
		default: 'discoverServices',
	},
	{
		displayName: 'Options',
		name: 'discoverOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['discovery'], operation: ['discoverServices'] } },
		options: [
			{
				displayName: 'Category',
				name: 'category',
				type: 'options',
				options: [
					{ name: 'Analytics', value: 'analytics' },
					{ name: 'Business Partner', value: 'business-partner' },
					{ name: 'Cross-Application', value: 'cross-application' },
					{ name: 'Finance', value: 'finance' },
					{ name: 'HR', value: 'hr' },
					{ name: 'Logistics', value: 'logistics' },
					{ name: 'Master Data', value: 'master-data' },
					{ name: 'Material', value: 'material' },
					{ name: 'Plant Maintenance', value: 'plant-maintenance' },
					{ name: 'Procurement', value: 'procurement' },
					{ name: 'Production', value: 'production' },
					{ name: 'Project', value: 'project' },
					{ name: 'Quality', value: 'quality' },
					{ name: 'Sales', value: 'sales' },
					{ name: 'Unknown', value: 'unknown' },
					{ name: 'Warehouse', value: 'warehouse' },
				],
				default: 'sales',
				description: 'Business domain to filter by',
			},
			{
				displayName: 'Limit',
				name: 'limit',
				type: 'number',
				default: 50,
				typeOptions: { minValue: 1, maxValue: 1000 },
				description: 'Max number of results to return',
			},
			{
				displayName: 'Offset',
				name: 'offset',
				type: 'number',
				default: 0,
				description: 'Number of services to skip (paging)',
			},
			{
				displayName: 'Search',
				name: 'search',
				type: 'string',
				default: '',
				description: 'Free-text search across name, title and description',
			},
		],
	},
	{
		displayName: 'Options',
		name: 'listOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['discovery'], operation: ['listServices'] } },
		options: [
			{
				displayName: 'Skip',
				name: 'skip',
				type: 'number',
				default: 0,
				description: 'Number of entity sets to skip (paging)',
			},
			{
				displayName: 'Top',
				name: 'top',
				type: 'number',
				default: 50,
				typeOptions: { minValue: 1, maxValue: 1000 },
				description: 'Maximum number of entity sets to return',
			},
		],
	},
	{
		displayName: 'Options',
		name: 'metadataOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['discovery'], operation: ['getMetadata'] } },
		options: [
			{
				displayName: 'Entity Type',
				name: 'entityType',
				type: 'string',
				default: '',
				description: 'Restrict to one entity type for full property details',
			},
			{
				displayName: 'Search',
				name: 'search',
				type: 'string',
				default: '',
				description: 'Filter entity types/sets by name pattern (case-insensitive)',
			},
		],
	},

	// -----------------------------------------------------------------------
	// IDoc
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['idoc'] } },
		options: [
			{
				name: 'Discover Types',
				value: 'discover',
				description: 'List IDoc types and segments from the metadata service',
				action: 'Discover types',
			},
			{
				name: 'Get Status',
				value: 'status',
				description: 'Processing status of an IDoc by document number',
				action: 'Get status',
			},
			{
				name: 'List Received',
				value: 'listReceived',
				description: 'IDocs SAP posted to the server’s /idoc webhook',
				action: 'List received documents',
			},
			{
				name: 'Send',
				value: 'send',
				description: 'Send an IDoc to SAP over HTTP/XML (server must run with the idoc tier and --allow-write)',
				action: 'Send a document',
			},
		],
		default: 'send',
	},
	{
		displayName: 'IDoc Type',
		name: 'idocType',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'ORDERS05',
		description: 'IDoc basic type, e.g. MATMAS05 or ORDERS05',
		displayOptions: { show: { resource: ['idoc'], operation: ['send'] } },
	},
	{
		displayName: 'Segments',
		name: 'segments',
		type: 'json',
		required: true,
		default:
			'[\n  {\n    "name": "E1EDK01",\n    "fields": { "CURCY": "EUR" },\n    "children": []\n  }\n]',
		description:
			'IDoc data segments as JSON array of { name, fields, children? } (up to three nesting levels)',
		displayOptions: { show: { resource: ['idoc'], operation: ['send'] } },
	},
	{
		displayName: 'Options',
		name: 'idocOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['idoc'], operation: ['send'] } },
		options: [
			{
				displayName: 'Message Type',
				name: 'mesType',
				type: 'string',
				default: '',
				description: 'Override the auto-derived message type (MESTYP)',
			},
			{
				displayName: 'Metadata Service URL',
				name: 'metadataServiceUrl',
				type: 'string',
				default: '',
				description: 'OData service for IDoc metadata — when set, segments are validated before sending',
			},
			{
				displayName: 'Receiver Partner Number',
				name: 'rcvprn',
				type: 'string',
				default: '',
				description: 'Override the receiver partner number (RCVPRN)',
			},
			{
				displayName: 'Receiver Port',
				name: 'rcvpor',
				type: 'string',
				default: '',
				description: 'Override the receiver port (RCVPOR)',
			},
			{
				displayName: 'Sender Partner Number',
				name: 'sndprn',
				type: 'string',
				default: '',
				description: 'Override the sender partner number (SNDPRN)',
			},
			{
				displayName: 'Sender Port',
				name: 'sndpor',
				type: 'string',
				default: '',
				description: 'Override the sender port (SNDPOR)',
			},
		],
	},
	{
		displayName: 'Document Number',
		name: 'docnum',
		type: 'string',
		required: true,
		default: '',
		description: 'IDoc document number (DOCNUM)',
		displayOptions: { show: { resource: ['idoc'], operation: ['status'] } },
	},
	{
		displayName: 'Status Service URL',
		name: 'statusServiceUrl',
		type: 'string',
		required: true,
		default: '',
		description: 'OData service used for the IDoc status query',
		displayOptions: { show: { resource: ['idoc'], operation: ['status'] } },
	},
	{
		displayName: 'Metadata Service URL',
		name: 'metadataServiceUrl',
		type: 'string',
		required: true,
		default: '',
		description: 'OData service that exposes IDoc metadata',
		displayOptions: { show: { resource: ['idoc'], operation: ['discover'] } },
	},

	// -----------------------------------------------------------------------
	// Tool (generic)
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['tool'] } },
		options: [
			{
				name: 'Call Tool',
				value: 'call',
				description: 'Call any tool the server exposes, with raw JSON arguments',
				action: 'Call a server tool',
			},
			{
				name: 'List Tools',
				value: 'list',
				description: 'Tools the server exposes for this token (name, description, input schema)',
				action: 'List server tools',
			},
		],
		default: 'call',
	},
	{
		displayName: 'Tool Name or ID',
		name: 'toolName',
		type: 'options',
		typeOptions: { loadOptionsMethod: 'getTools' },
		required: true,
		default: '',
		description:
			'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
		displayOptions: { show: { resource: ['tool'], operation: ['call'] } },
	},
	{
		displayName: 'Arguments',
		name: 'arguments',
		type: 'json',
		default: '{}',
		description: 'Tool arguments as JSON object — see List Tools for the input schema',
		displayOptions: { show: { resource: ['tool'], operation: ['call'] } },
	},
];
